name: game
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  image: ^4.2.0
  equatable: ^2.0.5
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_reorderable_grid_view: ^5.0.0
  just_audio: ^0.9.38

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sound/
    - assets/animals.jpg
